### ISSUE TITLE
Request for Node version increase

### ISSUE THREAD

**Issue by surensth** [MakeAndDevelop/firebase-appversion#1]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, MakeAndDevelop/firebase-appversion@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**SInce Node version used in this repo has been deprecated, is there any chance for this repo to upgrade the node version?**

**Comment by MakeAndDevelop** [comment]
Hi @surensth, thanks for submitting the issue! The action is now upgraded to Node.js 20. If you upgrade to `MakeAndDevelop/firebase-appversion@v2` you should be good to go.
